### ISSUE TITLE
Repeat / All Day?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/date_basic#11]
@Graham-72, it looks like Date Repeat and Date All Day have been removed from this module -- is that intentional?

**Comment by Graham-72** [comment]
@laryn, yes it was intentional. Please note that this module is superseded by Date becoming part of core, and this module was intentionally slimmed down before being significantly adapted for core. 

I created separate contrib modules for Date Repeat and Date All Day but have neglected them for many months. Initially I was hoping to import Calendar but hit other difficulties and ended up using Google Calendar in my project.

**Comment by laryn** [comment]
@Graham-72 Thanks -- I'll look for the repeat and all day modules! Do you have a record (or memory) of what the difficulties with Calendar were?

**Comment by Graham-72** [comment]
@laryn I wrote something about it at https://github.com/backdrop-contrib/calendar/issues/1
